-- Add migration script here

-- Add new columns to stock_prices table
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS change FLOAT NOT NULL DEFAULT 0.0;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS change_percent FLOAT NOT NULL DEFAULT 0.0;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS turnover BIGINT NOT NULL DEFAULT 0;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS transactions BIGINT NOT NULL DEFAULT 0;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS pe_ratio FLOAT;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS pb_ratio FLOAT;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS dividend_yield FLOAT;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS market_cap BIGINT;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS foreign_buy BIGINT;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS trust_buy BIGINT;
ALTER TABLE stock_prices ADD COLUMN IF NOT EXISTS dealer_buy BIGINT;
